language: python
python:
  - "2.7"
  - "3.3"
env:
  matrix:
   - DJANGO="Django<1.9"
   - DJANGO="Django==1.9b1"
# command to install dependencies
install:
  - "pip install -q -e ."
  - "pip install -q -r demo/requirements.txt"
  - pip install "$DJANGO"

# command to run tests
script: "cd demo && python manage.py test plans"
