language: python
python:
  - "2.7"
  - "3.3"
env:
  matrix:
   - DJANGO="Django<1.9"
branches:
  only:
    - master
# command to install dependencies
install:
  - "pip install -q -e ."
  - "pip install -q -r demo/requirements.txt"
  - pip install "$DJANGO"
  - pip install python-coveralls
  - pip install coverage

# command to run tests
script: "coverage run manage.py test plans"

after_success:
  - coveralls
